#theme: jekyll-theme-cayman
#theme: just-the-docs
#remote_theme: just-the-docs/just-the-docs
search_enabled: true

title: BlogSploit
description: A collection of ramblings based on IT, Cyber Security and Cloud Native
show_downloads: false
logo: /assets/imgs/TrollBS.jpg
